# -*- coding: utf-8 -*-
"""generate text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmbTCwF95vVWREtV-D4us0FsP3YkAycR
"""

!pip install transformers torch

from transformers import pipeline
generator=pipeline("text-generation",model="gpt2")
prompt="Artificial Intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text")
print(result[0]['generated-text'])

!pip install sentence_transformers

model = SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter Text 1:")
text2=input("Enter Text 2:")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("Similarity Score:",round(float(similarity),2))
if similarity>0.75:
  print("similarity level:High")
elif similarity >0.4:
  print("similarity level:Medium")
else:
  print("similarity level:Low")