# -*- coding: utf-8 -*-
"""MeetingMinutes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWv917dQfSNl0AODax_WnA6IEFlx6JlD
"""

import pandas as pd
from datetime import datetime
print("Meeting Minutes Generator\n")
meeting_title=input("enter meeting title:")
date=input("enter date of meeting:")
time=input("enter time of meeting:")
participants=input("enter participants(comma separated):")
agenda=input("enter agenda points(comma separated):")
decisions=input("enter decisions(comma separated):")
action_items=input("enter action items(comma separated):")
prapared_by=input("prapared by")
participants_list=[p.strip() for p in participants.split(",")if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",")if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",")if d.strip()]
action_list=[a.strip() for a in action_items.split(",")if a.strip()]
minutes={
    "meeting_title":meeting_title,
    "date":date,
    "time":time,
    "participants":",".join(participants_list),
    "agenda":";".join(agenda_list),
    "decisions taken":";".join(decisions_list),
    "action items":";".join(action_list),
    "prepared by":prapared_by,
    "generated_at":datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}
df=pd.DataFrame(list(minutes.items()),columns=["Field","Details"])
print("\n Meeting Minutes Generated Successfully\n")
display(df)
df.to_csv("Meeting minutes.csv",index=False)
print("Minutes saves to meeting_minutes.csv")