# -*- coding: utf-8 -*-
"""sentencesimilarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtteocEAbHp0r8NSxH7DCaVOqfPg8E0n
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1=input("enter text1: ")
text2=input("enter text2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\nsimilarity score:",round(float(similarity),2))
if similarity>0.75:
  print("Similarity level:High")
elif similarity>0.5:
  print("Similarity level:Medium")
else:
  print("Similarity level:Low")